import { Card } from "@gwent/shared-types";

const FACTION = "monsters" as const;

export const monstersCards: Card[] = [
  // Necrophages - Melee focused but some agile
  {
    // ABILITY: MUSTER
    id: "gwint_card_arachas1",
    name: "Arachas",
    power: 4,
    basePower: 4,
    faction: FACTION,
    type: "unit",
    allowedRows: ["melee"],
    isHero: false,
    description: "Ugly - nature's way of saying 'Stay the fuck away.'",
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_arachas2",
    name: "Arachas",
    power: 4,
    basePower: 4,
    faction: FACTION,
    type: "unit",
    allowedRows: ["melee"],
    isHero: false,
    description: "Ugly - nature's way of saying 'Stay the fuck away.'",
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_arachas3",
    name: "Arachas",
    power: 4,
    basePower: 4,
    faction: FACTION,
    type: "unit",
    allowedRows: ["melee"],
    isHero: false,
    description: "Ugly - nature's way of saying 'Stay the fuck away.'",
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_arachas_behemoth",
    name: "Botchling",
    power: 6,
    basePower: 6,
    faction: FACTION,
    type: "unit",
    allowedRows: ["siege"],
    isHero: false,
    description:
      "Like a cross between a crab, a spider...and a ploughin' mountain",
  },
  {
    id: "gwint_card_botchling",
    name: "Botchling",
    description:
      "Admit your mistakes and bury them proper - else they'll come back to haunt you.",
    type: "unit",
    basePower: 4,
    power: 4,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_celaeno_harpy",
    name: "Celaeno Harpy",
    description:
      "Common harpies feed on carrion. Celaeno harpies... they feed on dreams.",
    type: "unit",
    basePower: 2,
    power: 2,
    allowedRows: ["melee", "ranged"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_cockatrice",
    name: "Cockatrice",
    description:
      "Born of an egg laid by a cockerel... if you believe such peasant drivel.",
    type: "unit",
    basePower: 2,
    power: 2,
    allowedRows: ["ranged"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_crone_brewess",
    name: "Crone: Brewess",
    description: "We'll cut you up, boy. A fine broth you will make.",
    type: "unit",
    basePower: 6,
    power: 6,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_crone_weavess",
    name: "Crone: Weavess",
    description: "I sense your pain. I see you fear...",
    type: "unit",
    basePower: 6,
    power: 6,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_crone_whispess",
    name: "Crone: Whispess",
    description: "I'd be your best - and last.",
    type: "unit",
    basePower: 6,
    power: 6,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_draug",
    name: "Draug",
    description:
      "Some men cannot admit defeat. Some keep fighting from beyond the grave.",
    type: "unit",
    basePower: 10,
    power: 10,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: true,
  },
  {
    id: "gwint_card_earth_elemental",
    name: "Earth Elemental",
    description:
      "How to fight an earth elemental? You don't. You run. Fast as you can.",
    type: "unit",
    basePower: 6,
    power: 6,
    allowedRows: ["siege"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_endrega",
    name: "Endrega",
    description:
      "The nest! Take out the nest, or the bastards'll just keep coming!",
    type: "unit",
    basePower: 2,
    power: 2,
    allowedRows: ["ranged"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_fiend",
    name: "Fiend",
    description: "A fiend looks a bit like a deer. An enormous, evil deer.",
    type: "unit",
    basePower: 6,
    power: 6,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_fire_elemental",
    name: "Fire Elemental",
    description: "Fire is so delightful.",
    type: "unit",
    basePower: 6,
    power: 6,
    allowedRows: ["siege"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_foglet",
    name: "Foglet",
    description:
      "Fog creeps on little cat feet. Foglets creep over the bodies of their victims.",
    type: "unit",
    basePower: 2,
    power: 2,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_forktail",
    name: "Forktail",
    description: "Fork tails... Bah! Fuckers' tails're more like cleavers.",
    type: "unit",
    basePower: 5,
    power: 5,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_frightener",
    name: "Frightener",
    description:
      '"What have I done?" the mage cried out, frightened of his own creation.',
    type: "unit",
    basePower: 5,
    power: 5,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_gargoyle",
    name: "Gargoyle",
    description:
      '"What have I done?" the mage cried out, frightened of his own creation.',
    type: "unit",
    basePower: 2,
    power: 2,
    allowedRows: ["ranged"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_ghoul1",
    name: "Ghoul",
    description:
      "If ghouls are part of the Circle of Life... then it's a damn vicious circle.",
    type: "unit",
    basePower: 1,
    power: 1,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_ghoul2",
    name: "Ghoul",
    description:
      "If ghouls are part of the Circle of Life... then it's a damn vicious circle.",
    type: "unit",
    basePower: 1,
    power: 1,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_ghoul3",
    name: "Ghoul",
    description:
      "If ghouls are part of the Circle of Life... then it's a damn vicious circle.",
    type: "unit",
    basePower: 1,
    power: 1,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_grave_hag",
    name: "Grave Hag",
    description:
      "Their long tongues're for slurping marrow - and whipping prep.",
    type: "unit",
    basePower: 5,
    power: 5,
    allowedRows: ["ranged"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_griffin",
    name: "Griffin",
    description:
      "Griffins like to toy with their prey. Eat 'em alive, piece by piece.",
    type: "unit",
    basePower: 5,
    power: 5,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_harpy",
    name: "Harpy",
    description: "There are many species of harpy, and all are kleptomaniacs.",
    type: "unit",
    basePower: 2,
    power: 2,
    allowedRows: ["melee", "ranged"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_ice_giant",
    name: "Ice Gaint",
    description:
      "Fled one time in my life. From the Ice Giant. And I'm not a bit ashamed.",
    type: "unit",
    basePower: 5,
    power: 5,
    allowedRows: ["siege"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_imlerith",
    name: "Imlerith",
    description: "Ladd nahw! Kill them! Litter the earth with their entrails!",
    type: "unit",
    basePower: 10,
    power: 10,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: true,
  },
  {
    // ABILITY: BOOST
    id: "gwint_card_kayran",
    name: "Kayran",
    description:
      "Kill a kayran? Simple. Take your best sword... then sell it and hire a witcher.",
    type: "unit",
    basePower: 8,
    power: 8,
    allowedRows: ["melee", "ranged"],
    faction: FACTION,
    isHero: true,
  },
  {
    id: "gwint_card_leshen",
    name: "Leshen",
    description:
      "We never hunt in these woods. Not even if it means the whole village starves.",
    type: "unit",
    basePower: 10,
    power: 10,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: true,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_nekker1",
    name: "Nekker",
    description:
      "Damn things are almost cute, if you ignore the whole vicious killer aspect.",
    type: "unit",
    basePower: 2,
    power: 2,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_nekker2",
    name: "Nekker",
    description:
      "Damn things are almost cute, if you ignore the whole vicious killer aspect.",
    type: "unit",
    basePower: 2,
    power: 2,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_nekker3",
    name: "Nekker",
    description:
      "Damn things are almost cute, if you ignore the whole vicious killer aspect.",
    type: "unit",
    basePower: 2,
    power: 2,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_plague_maiden",
    name: "Plague Maiden",
    description:
      "The sick rave about a boil-pocked woman surrounded by herds of rabid rats...",
    type: "unit",
    basePower: 5,
    power: 5,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: SCORCH
    id: "gwint_card_toad",
    name: "Toad",
    description: "Big. Bad. Ugly. Squats in the sewers.",
    type: "unit",
    basePower: 7,
    power: 7,
    allowedRows: ["ranged"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_bruxa",
    name: "Vampire: Bruxa",
    description:
      "A vile, bloodthirsty, man-eating hag. Kind of like my mother-in-law.",
    type: "unit",
    basePower: 4,
    power: 4,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_ekimmara",
    name: "Vampire: Ekimmara",
    description:
      "Who would think overgrown bats would have a taste for gaudy jewelry?",
    type: "unit",
    basePower: 4,
    power: 4,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_fleder",
    name: "Vampire: Fleder",
    description:
      "Higher vampires embrace their victims. Fleders rip them to shreds.",
    type: "unit",
    basePower: 4,
    power: 4,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_garkain",
    name: "Vampire: Garkain",
    description:
      "Blood-drinkers and corpse-eaters so foul their very ugliness paralyses foes.",
    type: "unit",
    basePower: 4,
    power: 4,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_katakan",
    name: "Vampire: Katakan",
    description: "Drinking the blood of the Continent since the Conjunction.",
    type: "unit",
    basePower: 4,
    power: 4,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_werewolf",
    name: "Werewolf",
    description:
      "Wolves aren't as bad as they say. Werewolves, though - they're worse.",
    type: "unit",
    basePower: 5,
    power: 5,
    allowedRows: ["melee"],
    faction: FACTION,
    isHero: false,
  },
  {
    id: "gwint_card_wyvern",
    name: "Wyvern",
    description:
      "Imagine a cross between a winged snake and a nightmare. Wyverns are worse.",
    type: "unit",
    basePower: 2,
    power: 2,
    allowedRows: ["ranged"],
    faction: FACTION,
    isHero: false,
  },
];
