import { Card } from "@gwent/shared-types";

const FACTION = "scoia-tael" as const;

export const scoiaTaelCards: Card[] = [
  {
    id: "gwint_card_barclay",
    name: "Barclay Els",
    power: 6,
    basePower: 6,
    faction: FACTION,
    allowedRows: ["melee", "ranged"],
    description:
      "Our mead smells like piss, do it? Easy to fix - I'll break your fuckin' nose!",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_ciaran",
    name: "Ciaran aep Easnillien",
    power: 6,
    basePower: 6,
    faction: FACTION,
    allowedRows: ["melee", "ranged"],
    description: "The path to freedom is paved in blood, not ink.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_dennis",
    name: "Dennis Cramer",
    power: 6,
    basePower: 6,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "I know how to carry out orders, so you can shove your advice up your coal chute.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_dol_archer",
    name: "Dol Blathanna Archer",
    power: 4,
    basePower: 4,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "Take another step, dh'oine. You'd look better with an arrow between your eyes.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_dol_infantry1",
    name: "Dol Blathanna Scout",
    power: 6,
    basePower: 6,
    faction: FACTION,
    allowedRows: ["melee", "ranged"],
    description:
      "They track like hounds, run like deer and kill like cold-hearted bastards.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_dol_infantry2",
    name: "Dol Blathanna Scout",
    power: 6,
    basePower: 6,
    faction: FACTION,
    allowedRows: ["melee", "ranged"],
    description:
      "They track like hounds, run like deer and kill like cold-hearted bastards.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_dol_infantry3",
    name: "Dol Blathanna Scout",
    power: 6,
    basePower: 6,
    faction: FACTION,
    allowedRows: ["melee", "ranged"],
    description:
      "They track like hounds, run like deer and kill like cold-hearted bastards.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_dol_dwarf1",
    name: "Dwarven Skirmisher",
    power: 3,
    basePower: 3,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "Worked a pickaxe all me life. Battleaxe won't be any trouble.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_dol_dwarf2",
    name: "Dwarven Skirmisher",
    power: 3,
    basePower: 3,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "Worked a pickaxe all me life. Battleaxe won't be any trouble.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_dol_dwarf3",
    name: "Dwarven Skirmisher",
    power: 3,
    basePower: 3,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "Worked a pickaxe all me life. Battleaxe won't be any trouble.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_eithne",
    name: "Eithné",
    power: 10,
    basePower: 10,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "The dryad queen has eyes of molten silver, and a heart of cold-forged steel.",
    type: "unit",
    isHero: true,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_elf_skirmisher1",
    name: "Elven Skirmisher",
    power: 2,
    basePower: 2,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "No matter what you may have heard, elves don't take human scalps. Too much lice.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_elf_skirmisher2",
    name: "Elven Skirmisher",
    power: 2,
    basePower: 2,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "No matter what you may have heard, elves don't take human scalps. Too much lice.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_elf_skirmisher3",
    name: "Elven Skirmisher",
    power: 2,
    basePower: 2,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "No matter what you may have heard, elves don't take human scalps. Too much lice.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_filavandrel",
    name: "Filavandrel aen Fidhail",
    power: 6,
    basePower: 6,
    faction: FACTION,
    allowedRows: ["melee", "ranged"],
    description:
      "Though we are now few and scattered, our hearts burn brighter than ever.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_filavandrel",
    name: "Filavandrel aen Fidhail",
    power: 6,
    basePower: 6,
    faction: FACTION,
    allowedRows: ["melee", "ranged"],
    description:
      "Though we are now few and scattered, our hearts burn brighter than ever.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MEDIC
    id: "gwint_card_havekar_nurse1",
    name: "Havekar Healer",
    power: 0,
    basePower: 0,
    faction: FACTION,
    allowedRows: ["ranged"],
    description: "Sure, I'll patch you up. Gonna cost you, though.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MEDIC
    id: "gwint_card_havekar_nurse2",
    name: "Havekar Healer",
    power: 0,
    basePower: 0,
    faction: FACTION,
    allowedRows: ["ranged"],
    description: "Sure, I'll patch you up. Gonna cost you, though.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MEDIC
    id: "gwint_card_havekar_nurse3",
    name: "Havekar Healer",
    power: 0,
    basePower: 0,
    faction: FACTION,
    allowedRows: ["ranged"],
    description: "Sure, I'll patch you up. Gonna cost you, though.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_havekar_support1",
    name: "Havekar Smuggler",
    power: 5,
    basePower: 5,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "I fight for whoever's paying the best. Or whoever's easiest to rob.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_havekar_support2",
    name: "Havekar Smuggler",
    power: 5,
    basePower: 5,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "I fight for whoever's paying the best. Or whoever's easiest to rob.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: MUSTER
    id: "gwint_card_havekar_support3",
    name: "Havekar Smuggler",
    power: 5,
    basePower: 5,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "I fight for whoever's paying the best. Or whoever's easiest to rob.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_ida",
    name: "Ida Emean aep Sivney",
    power: 6,
    basePower: 6,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "I am a Sage. My power lies in possessing knowledge. Not sharing it.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_iorveth",
    name: "Iorveth",
    power: 10,
    basePower: 10,
    faction: FACTION,
    allowedRows: ["ranged"],
    description: "King or beggar, what's the difference? One dh'oine less.",
    type: "unit",
    isHero: true,
  },
  {
    id: "gwint_card_iorveth",
    name: "Iorveth",
    power: 10,
    basePower: 10,
    faction: FACTION,
    allowedRows: ["ranged"],
    description: "King or beggar, what's the difference? One dh'oine less.",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: SUPPORT
    id: "gwint_card_isengrim",
    name: "Isengrim Faoiltiarna",
    power: 10,
    basePower: 10,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "It dawns on them once they notice my scar: a realization of imminent death.",
    type: "unit",
    isHero: true,
  },
  {
    id: "gwint_card_mahakaman1",
    name: "Mahakaman Defender",
    power: 5,
    basePower: 5,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_mahakaman2",
    name: "Mahakaman Defender",
    power: 5,
    basePower: 5,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_mahakaman3",
    name: "Mahakaman Defender",
    power: 5,
    basePower: 5,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_mahakaman4",
    name: "Mahakaman Defender",
    power: 5,
    basePower: 5,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_mahakaman5",
    name: "Mahakaman Defender",
    power: 5,
    basePower: 5,
    faction: FACTION,
    allowedRows: ["melee"],
    description:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    type: "unit",
    isHero: false,
  },
  {
    // ABILITY: BOOST
    id: "gwint_card_milva",
    name: "Milva",
    power: 10,
    basePower: 10,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "With each arrow I loose, I think of my da. He'd be proud. I think.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_riordan",
    name: "Riordan",
    power: 1,
    basePower: 1,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "Stare into their eyes, feast on their terror. Then go in for the kill.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_saskia",
    name: "Saesenthessis",
    power: 10,
    basePower: 10,
    faction: FACTION,
    allowedRows: ["ranged"],
    description: "Beautiful, pure, fierce - the prefect icon for a rebellion.",
    type: "unit",
    isHero: true,
  },
  {
    // ABILITY: SCORCH
    id: "gwint_card_schirru",
    name: "Schirrú",
    power: 8,
    basePower: 8,
    faction: FACTION,
    allowedRows: ["siege"],
    description: "Time to look death in the face.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_schirru",
    name: "Toruviel",
    power: 2,
    basePower: 2,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "'d gladly kill you from up close, stare in your eyes... But you reek, human.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_schirru",
    name: "Toruviel",
    power: 2,
    basePower: 2,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "I'd gladly kill you from up close, stare in your eyes... But you reek, human.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_vrihedd_cadet",
    name: "Vrihedd Brigade Recruit",
    power: 4,
    basePower: 4,
    faction: FACTION,
    allowedRows: ["ranged"],
    description:
      "Hatred burns brighter than any fire, and cuts deeper than any blade.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_vrihedd_brigade1",
    name: "Vrihedd Brigade Veteran",
    power: 5,
    basePower: 5,
    faction: FACTION,
    allowedRows: ["melee", "ranged"],
    description:
      "Hatred burns brighter than any fire, and cuts deeper than any blade.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_vrihedd_brigade2",
    name: "Vrihedd Brigade Veteran",
    power: 5,
    basePower: 5,
    faction: FACTION,
    allowedRows: ["melee", "ranged"],
    description:
      "Hatred burns brighter than any fire, and cuts deeper than any blade.",
    type: "unit",
    isHero: false,
  },
  {
    id: "gwint_card_yaevinn",
    name: "Yaevinn",
    power: 6,
    basePower: 6,
    faction: FACTION,
    allowedRows: ["melee", "ranged"],
    description:
      "We are the drops of rain that together make a ferocious storm.",
    type: "unit",
    isHero: false,
  },
];
